type User {
  id: ID!
  username: String!
  email: String!
  password: String!
  posts: [Post!]!
  comments: [Comment!]!
}

type Post {
  id: ID!
  title: String!
  body: String!
  published: Boolean!
  author: User!
  comments: [Comment!]!
}

type Comment {
  id: ID!
  text: String!
  author: User!
  post: Post!
}

type Query {
  getPosts: [Post!]!
  getUsers: [User!]!
  getComments [Comment!]!
}

type Mutation {
  addPost(data: AddPostInput!): Post!
  addComment(data: AddCommentInput!): Comment!
  signupUser(data: SignupUserInput!): User!
}

type AddPostInput {
  title: String!
  imageUrl: String!
  categories: [String!]!
  description: String!
  author: User!
}

type SignupUserInput {
  username: String!
  email: String!
  password: String!
}

type AddCommentInput {
    text: String!
    author: User!
    post: Post!
}